executable = sub_condor.csh

output     = output/output_$(ProcId).out
error      = output/output_$(ProcId).err
log        = output/output_$(ProcId).log

getenv     = True

#environment = "X509_USER_PROXY=$ENV(HOME)/x509up_u61469"

requirements = (OpSysAndVer =?= "CentOS7")

#request_memory = 16000
#request_memory = 32000
request_memory = 48000

#+JobFlavour = "longlunch"
#+JobFlavour = "workday"
+JobFlavour = "tomorrow"

should_transfer_files = IF_NEEDED
when_to_transfer_output = ON_EXIT
transfer_output_files = ""

queue arguments from (
/eos/home-m/matheus/amostras_2016/merged_06_10_20/pre_MiniAOD_FPMC_WW_13TeV_0.0_0.0.root SM
/eos/home-m/matheus/amostras_2016/merged_06_10_20/pre_MiniAOD_FPMC_WW_13TeV_0.0_2e-5.root ANOMALO1
/eos/home-m/matheus/amostras_2016/merged_06_10_20/pre_MiniAOD_FPMC_WW_13TeV_0.0_2e-6.root ANOMALO2
/eos/home-m/matheus/amostras_2016/merged_06_10_20/pre_MiniAOD_FPMC_WW_13TeV_0.0_5e-6.root ANOMALO3
/eos/home-m/matheus/amostras_2016/merged_06_10_20/pre_MiniAOD_FPMC_WW_13TeV_0.0_8e-6.root ANOMALO4
/eos/home-m/matheus/amostras_2016/merged_06_10_20/pre_MiniAOD_FPMC_WW_13TeV_0.5e-6_0.0.root ANOMALO5
/eos/home-m/matheus/amostras_2016/merged_06_10_20/pre_MiniAOD_FPMC_WW_13TeV_1.0e-6_0.0.root ANOMALO6
/eos/home-m/matheus/amostras_2016/merged_06_10_20/pre_MiniAOD_FPMC_WW_13TeV_2.0e-6_0.0.root ANOMALO7
/eos/home-m/matheus/amostras_2016/merged_06_10_20/pre_MiniAOD_FPMC_WW_13TeV_5.0e-6_0.0.root ANOMALO8
)
